import arcade

#ARCADE WINDOW
SCREEN_TITLE = "Dino Run"
SCREEN_WIDTH = 820
SCREEN_HEIGHT = 480


#SCORE
SCORE_X = 100
SCORE_Y = 100
SCORE_STARTING_VALUE = 0
SCORE_FONT_SIZE = 10
SCORE_COLOR = arcade.color.BLACK


#MENU
MENU_BACKGROUND_COLOR = arcade.color.BLACK
MENU_FONT = "calibri"
MENU_BACKUP_FONT = "arial"
MENU_FONT_SIZE = 10
MENU_FONT_COLOR = arcade.color.WHITE
MENU_BUTTON_BACKGROUND_COLOR = arcade.color.DARK_BLUE_GRAY
MENU_BUTTON_PRESS_BACKGROUND_COLOR = arcade.color.WHITE
MENU_BUTTON_PRESS_FONT_COLOR = arcade.color.DARK_BLUE_GRAY
MENU_BUTTON_BORDER_COLOR = arcade.color.WHITE
MENU_BUTTON_PRESS_BORDER_COLOR = arcade.color.BLACK
MENU_BUTTON_BORDER_WIDTH = 2


#Player
SPRITE_SCALING_BOX = 0.5
SPRITE_SCALING_PLAYER = 3
SPRITE_SCALING = 0.5
MOVEMENT_SPEED = 3
SPRINT_SPEED = 5
SLOW_SPEED = 1.5
SPRINT_COOLDOWN = 30 #frames
JUMP_SPEED = 7
UPDATES_PER_FRAME = 5
IDLE_UPDATES_PER_FRAME = 13
CHARACTER_SCALING = 0.3
GRAVITY = 0.7


# Layer Names from our TileMap
LAYER_NAME_PLATFORMS = "Platform"
LAYER_NAME_FLOOR = "Floor"
LAYER_NAME_CHECKPOINT = "Checkpoint"
LAYER_NAME_FOREGROUND = "Foreground"
LAYER_NAME_BACKGROUND = "Background"
LAYER_NAME_GATES = "Gates"
TILE_SCALING = 1

LAYER_OPTIONS = {
    LAYER_NAME_PLATFORMS: {
        "use_spatial_hash": False,
    },
    LAYER_NAME_FLOOR: {
        "use_spatial_hash": False,
    },
    LAYER_NAME_CHECKPOINT: {
        "use_spatial_hash": True,
    },
}
