import arcade

#ARCADE WINDOW
SCREEN_WIDTH = 640
SCREEN_HEIGHT = 480


#SCORE
SCORE_X = 100
SCORE_Y = 100
SCORE_STARTING_VALUE = 0
SCORE_FONT_SIZE = 10
SCORE_COLOR = arcade.color.BLACK


#MENU
MENU_BACKGROUND_COLOR = arcade.color.BLACK
MENU_FONT = "calibri"
MENU_BACKUP_FONT = "arial"
MENU_FONT_SIZE = 10
MENU_FONT_COLOR = arcade.color.WHITE
MENU_BUTTON_BACKGROUND_COLOR = arcade.color.DARK_BLUE_GRAY
MENU_BUTTON_PRESS_BACKGROUND_COLOR = arcade.color.WHITE
MENU_BUTTON_PRESS_FONT_COLOR = arcade.color.DARK_BLUE_GRAY
MENU_BUTTON_BORDER_COLOR = arcade.color.WHITE
MENU_BUTTON_PRESS_BORDER_COLOR = arcade.color.BLACK
MENU_BUTTON_BORDER_WIDTH = 2
